package com.wangshibiao.spring.dao;

import com.wangshibiao.spring.model.Org;
import com.wangshibiao.spring.model.OrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int countByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int deleteByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    List<Org> selectByExample(OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    Org selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") Org record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int updateByExample(@Param("record") Org record, @Param("example") OrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbggenerated Fri Jun 24 22:56:37 CST 2016
     */
    int updateByPrimaryKey(Org record);
}