
package com.wangshibiao.spring.oemsSoapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OemsSmsService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://116.213.120.55/OpenSMSWebService/OemsSmsService.asmx?wsdl")
public class OemsSmsService
    extends Service
{

    private final static URL OEMSSMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException OEMSSMSSERVICE_EXCEPTION;
    private final static QName OEMSSMSSERVICE_QNAME = new QName("http://tempuri.org/", "OemsSmsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://116.213.120.55/OpenSMSWebService/OemsSmsService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OEMSSMSSERVICE_WSDL_LOCATION = url;
        OEMSSMSSERVICE_EXCEPTION = e;
    }

    public OemsSmsService() {
        super(__getWsdlLocation(), OEMSSMSSERVICE_QNAME);
    }

    public OemsSmsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OEMSSMSSERVICE_QNAME, features);
    }

    public OemsSmsService(URL wsdlLocation) {
        super(wsdlLocation, OEMSSMSSERVICE_QNAME);
    }

    public OemsSmsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OEMSSMSSERVICE_QNAME, features);
    }

    public OemsSmsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OemsSmsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OemsSmsServiceSoap
     */
    @WebEndpoint(name = "OemsSmsServiceSoap")
    public OemsSmsServiceSoap getOemsSmsServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "OemsSmsServiceSoap"), OemsSmsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OemsSmsServiceSoap
     */
    @WebEndpoint(name = "OemsSmsServiceSoap")
    public OemsSmsServiceSoap getOemsSmsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "OemsSmsServiceSoap"), OemsSmsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OEMSSMSSERVICE_EXCEPTION!= null) {
            throw OEMSSMSSERVICE_EXCEPTION;
        }
        return OEMSSMSSERVICE_WSDL_LOCATION;
    }

}
