
package com.wangshibiao.spring.oemsSoapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OemsSmsServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OemsSmsServiceSoap {


    /**
     * 
     * @param smsSendSoapHeader
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.HelloWorldResponse")
    public String helloWorld(
        @WebParam(name = "SmsSendSoapHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "SmsSendSoapHeader")
        SmsSendSoapHeader smsSendSoapHeader);

    /**
     * 带SoapHeader的发送信息
     * 
     * @param smsSendResult
     * @param msgContent
     * @param returnValue
     * @param msgTitle
     * @param smsSendSoapHeader
     * @param mobilephoneno
     */
    @WebMethod(operationName = "SmsSend", action = "http://tempuri.org/SmsSend")
    @RequestWrapper(localName = "SmsSend", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.SmsSend")
    @ResponseWrapper(localName = "SmsSendResponse", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.SmsSendResponse")
    public void smsSend(
        @WebParam(name = "mobilephoneno", targetNamespace = "http://tempuri.org/")
        String mobilephoneno,
        @WebParam(name = "msgTitle", targetNamespace = "http://tempuri.org/")
        String msgTitle,
        @WebParam(name = "msgContent", targetNamespace = "http://tempuri.org/")
        String msgContent,
        @WebParam(name = "SmsSendResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<Integer> smsSendResult,
        @WebParam(name = "returnValue", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<String> returnValue,
        @WebParam(name = "SmsSendSoapHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "SmsSendSoapHeader")
        SmsSendSoapHeader smsSendSoapHeader);

    /**
     * 带SoapHeader的获取短信状态报告信息
     * 
     * @param smsSendSoapHeader
     * @return
     *     returns com.wangshibiao.spring.oemsSoapClient.ArrayOfString
     */
    @WebMethod(operationName = "MsgSendReportStatus", action = "http://tempuri.org/MsgSendReportStatus")
    @WebResult(name = "MsgSendReportStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MsgSendReportStatus", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.MsgSendReportStatus")
    @ResponseWrapper(localName = "MsgSendReportStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.MsgSendReportStatusResponse")
    public ArrayOfString msgSendReportStatus(
        @WebParam(name = "SmsSendSoapHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "SmsSendSoapHeader")
        SmsSendSoapHeader smsSendSoapHeader);

    /**
     * 带SoapHeader获取短信接收信息
     * 
     * @param smsSendSoapHeader
     * @return
     *     returns com.wangshibiao.spring.oemsSoapClient.ArrayOfString
     */
    @WebMethod(operationName = "MsgReceiveInfo", action = "http://tempuri.org/MsgReceiveInfo")
    @WebResult(name = "MsgReceiveInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MsgReceiveInfo", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.MsgReceiveInfo")
    @ResponseWrapper(localName = "MsgReceiveInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.wangshibiao.spring.oemsSoapClient.MsgReceiveInfoResponse")
    public ArrayOfString msgReceiveInfo(
        @WebParam(name = "SmsSendSoapHeader", targetNamespace = "http://tempuri.org/", header = true, partName = "SmsSendSoapHeader")
        SmsSendSoapHeader smsSendSoapHeader);

}
