CREATE TABLE org
(
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE user
(
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    age INT(11) NOT NULL,
    name VARCHAR(255) NOT NULL,
    orgId VARCHAR(255) NOT NULL
);