
package com.wangshibiao.spring.soapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Helloworld", targetNamespace = "http://soapServer.spring.wangshibiao.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Helloworld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soapServer.spring.wangshibiao.com/Helloworld/method1Request", output = "http://soapServer.spring.wangshibiao.com/Helloworld/method1Response")
    public String method1(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
